### ISSUE TITLE
Force case set to simplify Base32 processing

### ISSUE THREAD

**Issue by brianredbeard** [tschuy/gotp#11]
The [Base32][base32] character set intentionally avoids case sensitive characters so as to be safe for use on case-insensitive filesystems.  This leads to situations where some vendors (e.g. Amazon, CloudFlare) use all upper case characters while other vendors (e.g. Google, Stripe, Packet.net, Microsoft) use all lowercase.  

This currently leads to a situation where enrollment with lower case tokens fails with the following error:

```
[bharrington@leviathan ~]$ gotp  enroll -e brian.harrington@coreos.com -t GitHub
Paste secret: 
2017/07/12 09:35:25 invalid secret (was not base32!)
```

[base32]: https://en.wikipedia.org/wiki/Base32

**Comment by tschuy** [comment]
Fixed in https://github.com/tschuy/gotp/commit/5019a9edb47cf5e137c78364a85a9ed6bf2e49a8
